version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cmp
    networks:
      - backend
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - backend
networks:
  backend: